name: 🧪 Test Coverage

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]
  workflow_dispatch:

jobs:
  coverage-comment-raw:
    name: 📝 PR Raw Coverage Table
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci

      - name: Run coverage and extract table
        run: |
          npm run test:coverage > full-coverage.txt || true
          sed -n '/^-------------------------|---------|----------|---------|---------|/,$p' full-coverage.txt | \
          sed '/^=============================== Coverage summary ===============================/,$d' | \
          # Remove first and last border lines:
          sed '1d;$d' > coverage-table.txt

      - name: Comment test results
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "jest-coverage-raw"
          recreate: true
          path: coverage-table.txt

  coverage-comment:
    name: 📝 PR Coverage Summary
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run coverage
        run: npm run test:coverage
      - name: Comment coverage summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: reports/coverage/cobertura-coverage.xml
          badge: true
          format: markdown
          output: both
          indicators: true
      - name: Post coverage comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: "jest-coverage-summary"
          recreate: true
          path: code-coverage-results.md

  coverage-upload-codecov:
    name: 📤 Upload Coverage to Codecov
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4

      - name: ⏭ Skip tests & coverage
        if: github.event_name == 'pull_request' && (contains(github.event.pull_request.title, 'WIP') || contains(github.event.pull_request.title, '!COV'))
        run: |
          echo "Skipping tests and coverage upload due to PR title containing 'WIP' or '!COV'."
          exit 0

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run tests with coverage
        run: npm run test:coverage

      - name: 📤 Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: reports/coverage/lcov.info
          flags: unittests
          name: codecov-coverage-report
